AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*/rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: true

Rails:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Validation:
  Enabled: false

Rails/FindBy:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/MethodLength:
  Max: 29

Style/AccessorMethodName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/AsciiComments:
  Enabled: false
